### ISSUE TITLE
Would it be possible to expose 'carafe detect' disable/enable as a switch ?

### ISSUE THREAD

**Issue by brewston** [sergeymaysak/smartercoffee#1]
Sometimes, after a power cycle, my machine comes back with 'carafe detect' enabled. It's never worked very well for me and so the machine refuses to brew until I dig out an old phone (that has the app logged in!) and disable 'carafe detect' again. Thanks.

**Comment by sergeymaysak** [comment]
@brewston Hey Tim! Sure - just released build  [1.4.0](https://github.com/sergeymaysak/smartercoffee/releases/tag/1.4.0) with such addition per your request ) Enjoy!

**Comment by brewston** [comment]
Thankd for implementing it. I installed it but I think the logic is reversed. When 'carafe detection' was false in HA, I could see it was 'on' on the coffee machine (and vice versa)

**Comment by sergeymaysak** [comment]
> Thankd for implementing it. I installed it but I think the logic is reversed. When 'carafe detection' was false in HA, I could see it was 'on' on the coffee machine (and vice versa)

@brewston right ) my fault - catch new build with fix [1.4.1](https://github.com/sergeymaysak/smartercoffee/releases/tag/1.4.1)
