### ISSUE TITLE
Setup failed: Unable to import component: cannot import name 'CoroWrapper' from 'asyncio.coroutines' 

### ISSUE THREAD

**Issue by hdiessner** [sergeymaysak/smartercoffee#10]
After update to latest home-assistant release 2023.06.2 this integration fails to load - seem so be related to the update of Python to Version 3.11

Logger: homeassistant.setup
Source: setup.py:215
First occurred: 1:55:04 PM (1 occurrences)
Last logged: 1:55:04 PM

Setup failed for custom integration smartercoffee: Unable to import component: cannot import name 'CoroWrapper' from 'asyncio.coroutines' (/usr/local/lib/python3.11/asyncio/coroutines.py)

**Comment by brewston** [comment]
I fixed this in my branch -https://github.com/sergeymaysak/smartercoffee/commit/6234fa375f05054fdc23d9fc8fbefa114deb9adf

or you can just edit that file and comment the import on line 13 (which is all I did)

**Comment by hdiessner** [comment]
Wow, that was a quick and easy fix, thank you!
