### ISSUE TITLE
INstallation Issue

### ISSUE THREAD

**Issue by Peiloy** [sergeymaysak/smartercoffee#11]
When trying to add the integration, I get the following error: 

Config flow could not be loaded: {"message":"Invalid handler specified"}

This is what the log says:

Logger: homeassistant.config_entries
Source: config_entries.py:2069
First occurred: 15:48:27 (2 occurrences)
Last logged: 15:56:49

Error occurred loading flow for integration smartercoffee: cannot import name 'CoroWrapper' from 'asyncio.coroutines' (/usr/local/lib/python3.11/asyncio/coroutines.py)

I am on version:
Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

**Comment by brewston** [comment]
I fixed this in PR https://github.com/sergeymaysak/smartercoffee/pull/9  but it's not been integrated (Not sure what Sergey's circumstances are presently, so i think it's understandable) 

Your choice is to either edit __init__.py and comment out that import yourself (if that's something you are comfortable doing) or to use by branch which has the fix https://github.com/brewston/smartercoffee

**Comment by sergeymaysak** [comment]
Fixed in [release 17](https://github.com/sergeymaysak/smartercoffee/releases/tag/1.5.0).
