### ISSUE TITLE
De-scale reminder might be useful

### ISSUE THREAD

**Issue by brewston** [sergeymaysak/smartercoffee#2]
Just an input boolean like descale_required and a timer. When the boolean is set false, the timer waits for 90 days (or however often you de-scale) and flips to true again. I guess it could just be done outside the integration though.

**Comment by sergeymaysak** [comment]
I really think it should outside of integration (as it is not related to the actual hw of the coffee machine) and can be done by input_boolean, number etc of HA...

**Comment by brewston** [comment]
Fair enough :)
