### ISSUE TITLE
Invalid config error with HA 2022.2.0

### ISSUE THREAD

**Issue by hdiessner** [sergeymaysak/smartercoffee#6]
Thank you for your integration.
After Update to the latest HA Version 2022.2.0 there is an "Invalid config" error:
"The following integrations and platforms could not be set up:
smartercoffee.switch
smartercoffee.binary_sensor"

Apparently the switch and binary_sensor entities definitions in HA have changed.

**Comment by hdiessner** [comment]
Excerpt from the log file:
`ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform smartercoffee.binary_sensor: Platform not found (cannot import name 'BinarySensorDevice' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)).`
`ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform smartercoffee.switch: Platform not found (cannot import name 'SwitchDevice' from 'homeassistant.components.switch' (/usr/src/homeassistant/homeassistant/components/switch/__init__.py))`

**Comment by brewston** [comment]
I took a look, I could see where the device classes were removed but it wasn't obvious to me what replaced them. But when I then took a closer look at @sergeymaysak code, they were being imported but not being used. I removed the 2 import lines and restarted HA and it _seems_ its all back (Too late at night here to test making coffee :rofl: )

If you are comfortable making changes, remove :  

custom_components/smartercoffee/binary_sensor.py - line 11
custom_components/smartercoffee/switch.py - line 13

and restart HA

**Comment by sergeymaysak** [comment]
thanks, Tim! ) fixed in https://github.com/sergeymaysak/smartercoffee/releases/tag/1.4.5

**Comment by hdiessner** [comment]
You are awesome! Updated to the new fix and everything is working fine, again. Thank you!
