### ISSUE TITLE
2022.7.0 breaks this integration with "the loop parameter was removed from Lock() since it is no longer necessary"

### ISSUE THREAD

**Issue by brewston** [sergeymaysak/smartercoffee#7]
Looks like 2022.7.0 brought python 3.10 with it and _something_ used in this integration is now deprecated.

**Comment by sttvsttv** [comment]
Error: As of 3.10, the loop parameter was removed from Lock() since it is no longer necessary
Please restart hass after fixing this.

**Comment by brewston** [comment]
@sttvsttv I have a fix for this (Friend helped me, I don't understand async python) 

File : custom_components/smartercoffee/smartercontroller.py
Line 269 : Remove the param from the call to asyncio.Lock
ie 

Change : 

` self._io_lock = asyncio.Lock(loop=self.io_loop)`

to

` self._io_lock = asyncio.Lock()`

Restart HA and the integration loads and the entities are enabled.

**Comment by TeRRa4** [comment]
> @sttvsttv I have a fix for this (Friend helped me, I don't understand async python)
> 
> File : custom_components/smartercoffee/smartercontroller.py Line 269 : Remove the param from the call to asyncio.Lock ie
> 
> Change :
> 
> ` self._io_lock = asyncio.Lock(loop=self.io_loop)`
> 
> to
> 
> ` self._io_lock = asyncio.Lock()`
> 
> Restart HA and the integration loads and the entities are enabled.

This fixed it for me, thanks!

**Comment by sergeymaysak** [comment]
fixed in [1.4.7](https://github.com/sergeymaysak/smartercoffee/releases/tag/1.4.7)

**Comment by sttvsttv** [comment]
10X :)

**Comment by sergeymaysak** [comment]
I meant [1.4.8](https://github.com/sergeymaysak/smartercoffee/releases/tag/1.4.8) ))
Cheers!
