### ISSUE TITLE
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3

### ISSUE THREAD

**Issue by brewston** [sergeymaysak/smartercoffee#8]
Just noticed this in my logs. 

`Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for smartercoffee using this method at custom_components/smartercoffee/__init__.py, line 131: hass.config_entries.async_setup_platforms(self._config_entry, PLATFORMS)`

**Comment by brewston** [comment]
Proposed change :  

`__init__.py `- line 131 

Remove - `self.hass.config_entries.async_setup_platforms(self._config_entry, PLATFORMS)`

Replace with  - `await hass.config_entries.async_forward_entry_setups(self._config_entry, PLATFORMS)`

**Comment by sergeymaysak** [comment]
Fixed in [release 17](https://github.com/sergeymaysak/smartercoffee/releases/tag/1.5.0), thank you 
@brewston ) - you are good friend!, sorry for long silence.

**Comment by brewston** [comment]
I'm pleased to hear from you @sergeymaysak - I hope you and your family are keeping safe.
